--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
--INSERT INTO confirmations (token, is_error) VALUES ('AUTHORIZATION_FAILURE', 1);
